branches:
  only:
    - master
matrix:
  include:
    - name: "Swift Test"
      os: osx
      language: objective-c
      osx_image: xcode11.3
      script:
        - brew install libressl
        - swift test
